#!/bin/sh

if [ -z "$*" ]; then
    printf "\033[1;35m%s" "Enter the name of you .asm file : "
    read -r file
    trimmed=$(echo "$file" | cut -f 1 -d '.')
else
    file=$*
    trimmed=$(echo "$file" | cut -f 1 -d '.')
fi
touch $trimmed.o
gcc /usr/share/sasm/NASM/macro.c -c -o macro.o -m32 2>/dev/null &&
nasm $trimmed.asm -i /usr/share/sasm/include/ -f elf32 2>/dev/null &&
gcc -m32 $trimmed.o macro.o -o $trimmed 2>/dev/null &&
printf "\n"
printf "\033[1;35m%s\n\n" "Here is the output of your NASM programm:"
./$trimmed
printf "\n"
