#!/bin/bash

# ---------------------------------------------------------
# Name:   dmenu-reddit
# Author: Cyr4x3
# Descr.: Dmenu script for viewing specific subreddits via
# 				tuir (a terminal reddit viewer).
# ---------------------------------------------------------


declare -a options=("r/archlinux
r/bash
r/commandline
r/DistroTube
r/FirefoxCSS
r/freshalbumart
r/linux
r/linuxmasterrace
r/orslokx
r/Piracy
r/privacy
r/suckless
r/unixart
r/unixporn
r/vim
r/Yointerneto
r/xmonad
quit")

choice=$(echo -e "${options[@]}" | dmenu -l -i -p 'Reddit: ')

case "$choice" in
	quit)
		echo "Program terminated." && exit 1
	;;
	r/archlinux| \
	r/bash| \
	r/commandline| \
	r/DistroTube| \
  r/FirefoxCSS| \
  r/freshalbumart| \
	r/linux| \
	r/linuxmasterrace| \
  r/orslokx| \
  r/Piracy| \
  r/privacy| \
  r/suckless| \
	r/unixart| \
	r/unixporn| \
  r/vim| \
  r/Yointerneto| \
  r/xmonad)
	;;
	*)
		exit 1
	;;
esac
$BROWSER https://www.reddit.com/$choice

