#!/bin/sh
query="$(printf "Youtube\nLastSession\nArchWiki\n/g/4chan\nReddit\nDrive\nMeet\nGmail\nWhatsapp\nGithub\nHomepage\nunix_porn" | dmenu -i -p 'Search:')"
browser="$1"
[ -z "$query" ] && exit
check_url() {
	url="$(echo "$query" | grep -Eo '[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)')"
	if [ "$url" = "$query" ]; then
		"$browser" "$url"
	else
		"$browser" "https://search.brave.com/search?q=$query&source=desktop"
	fi
}
case "$query" in
    "LastSession") $BROWSER --restore-last-session ;;
    "Youtube") $BROWSER https://www.youtube.com ;;
    "Gmail") $BROWSER https://www.gmail.com ;;
    "Github") $BROWSER https://github.com/iamchokerman;;
    "ArchWiki") $BROWSER https://wiki.archlinux.org ;;
    "Homepage") $BROWSER;;
    "/g/4chan") $BROWSER https://boards.4channel.org/g/ ;;
    "Reddit") $BROWSER https://www.reddit.com ;;
    "Drive") $BROWSER https://drive.google.com/drive/u/0/my-drive ;;
    "Meet") $BROWSER https://meet.google.com/ ;;
    "Whatsapp") $BROWSER https://web.whatsapp.com/ ;;
    "unix_porn") $BROWSER https://www.reddit.com/r/unixporn/ ;;  
    *) check_url ;;
esac
