#!/bin/sh
query="$(: | dmenu -p "Search:")"
[ -z "$query" ] && exit
case $2 in
    "ArchWiki") $1 "https://wiki.archlinux.org/index.php?search=$query" ;;
    "Youtube") $1 "https://www.youtube.com/results?search_query=$query" ;;
    "Github") $1 "https://github.com/search?q=$query" ;;
    "Amazon") $1 "https://www.amazon.in/s?k=$query" ;;
    "Wikipedia") $1 "https://en.wikipedia.org/wiki/$query" ;;
    "Piratebay") $1 "https://thepiratebay.org/search.php?q=$query" ;;
    "Search") $1 "https://duckduckgo.com/?q=$query&t=h_&ia=web";;
    "YandexImages") $1 "https://yandex.ru/images/search?text=$query";;
    "CoteWiki") $1 "https://you-zitsu.fandom.com/wiki/Special:Search?query=$query&scope=internal&navigationSearch=true" ;;
    "Subreddits") $1 "https://www.reddit.com/r/$query" ;;
    "MyAnimeList") $1 "https://myanimelist.net/search/all?q=$query" ;;
esac
