#!/bin/sh
file="$(printf "pix\ndownloads\nwallpapers\nwallhaven\ncote_screenshots\nscreenshots\nanime_memes" | dmenu -p "Open:" -i -l 6)"
[ -z "$file" ] && exit

program="sxiv -t"
case $file in
    "pix") $program ~/pix;;
    "downloads") $program ~/Downloads ;;
    "wallpapers") $program ~/Pictures/wallpapers;;
    "wallhaven") $program ~/Pictures/wallhaven;;
    "cote_screenshots") $program /home/ivan/Pictures/cote_screenshots;;
    "screenshots") $program ~/Pictures/screenshots;;
    "anime_memes") $program /home/ivan/anime_memes;;
esac
