#!/bin/sh
export "XDG_RUNTIME_DIR"="/run/user/"$(id -u)""
doas pacman -Syuw --noconfirm > /dev/null
noofpack=$(doas pacman -Qu | wc -l 2> /dev/null)
case $noofpack in
    "1") notify-send -i /home/zenith71/.config/dunst/update.png "❗ Important ❗" "$noofpack package is not updated" ;;
    "0") ;;
    *) notify-send -i /home/zenith71/.config/dunst/update.png "❗ Important ❗" "$noofpack packages are not updated" ;;
esac

