#!/usr/bin/env python3

"""
torrentz - extract torrent links from a webpage.

Usage:
    torrentz https://yts.ag/*
    torrentz https://www.shaanig.org/*
"""

import sys
import urllib.parse

import pyquery


def get_torrent_links(source):
    """ Print all URLs that begin with 'magnet' or end with '.torrent' """

    pq = pyquery.PyQuery(url=source)

    # Prevents duplicate links
    seen = set()

    for a in pq.find('a'):
        href = a.get('href')

        if href and (href.startswith("magnet") or
                     href.endswith(".torrent") and
                     href not in seen and
                     "1080p" not in a.get('title', '')):

            seen.add(href)

            # Handle relative URLs
            if href.startswith("/"):
                url = urllib.parse.urlsplit(source)
                href = "%s://%s" % (url.scheme, url.netloc) + href

            print("%s %s" % (a.get('title', ''), href))
            print()


if __name__ == '__main__':
    get_torrent_links(sys.argv[1])
